---
title: "string and factor"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

#  String vector

detect string and replace them
```{r}
string_vec <-  c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff")

str_replace(string_vec,"jeff","Jeff")
```

detect string in special space
```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
# start with i think,"^..." means the beginning of the line,"...^"means the end of the line
str_detect(string_vec, "^i think")
str_detect(string_vec, "i think^")
```

detect with upper and lower case
```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

#"[]" means anything in the [] works
str_detect(string_vec,"[Bb]ush")
```

lower and upper case
```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

#"[][]" means the combination and you can conclude all the lower case
str_detect(string_vec, "^[0-9][a-zA-Z]")
```

the use of "."
```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

# "." means everything 
str_detect(string_vec, "7.11")
```

special symbol which have special meaning use \
```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

